language: python
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

python:
  - 3.6

install:
  - pip install -e psyche
  - pip install pytest flake8

script:
  - make test
  - CXX=g++-7 make style-check

notifications:
  email: false
